# .github/workflows/release.yml
name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required to push commits and tags

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    # Prevent the workflow from running on commits made by itself (e.g., the release commit)
    if: "contains(github.event.head_commit.message, 'chore(release)') == false"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use a PAT to bypass branch protection rules for the release commit.
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-python-3.13-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-3.13-uv-

      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install -e .[dev]

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Release Bump
        run: |
          source .venv/bin/activate
          # The "|| true" part ensures the workflow doesn't fail if no bump is needed (e.g., only docs changes)
          cz bump --changelog || true

      - name: Push changes
        run: git push --follow-tags
